language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
script:
  - sudo sh test/travis_ci_scripts/travis_ci_build_script.sh
  - python -m unittest discover
GITHUB_API_KEY:
  secure: "h4EZFxSfmj2bqbrtKwZu2bDK8brv4wDu518hQ8VLb7PgW82kRP1FAsmat6Ixs4DQlRtxcYLlQXoLqTMCjD9SpywqE1ba2jVAbtAUmhHVYVS0feT2eJ5yOKt9LhWFQdMKlVhMMXTzUlA7wy8qTRbPoAfNj5iat4Way3FRiLDeItt0AgwIGf2Qmq05wyXIqmOhefvbOYyKl4RGaOm1c9z5yUCpPSZRqs/zrj/8fRHkFRmq9Ng9d718+coTbU7DqqNfLJpEAoHiDWtB7qv2/5jke7LX9buYZAfCAvJS5xXgue+amjyebYTsT0Sd/sMPevVFrw6SZQtLlSUS03VWipYkD7SxpMiIV02EAfp+7djhgletPkcnGaEHMoRMYzvslJND0gRI2XRWSK71g18DcBZtY5R7HTG+AoZPcHy8teJhUJ2LKmhBLPHJWq3E1wSGTa1sDELcbNLtIAivDn8dl6i/iNWowT5G633Rr5BFhXpP63lQchlBPde6HeBWR5tZAjgYI184UApA3hJyxDOwuvG2UbW3MrIlD0LBm4O54UAoYIDk4IfNPsdBsuH/laShW/R0GVZD54Y+VgU64j1eHFEy8I8WlyjAtcXXzCnRGAyqqBexubh5v8nAtQNbToL4FkM3rvneXOdpyNUiNl2EhANtTfPIopsGOCjzmxC2hg3UlVE="
after_success:
  - chmod +x test/travis_ci_scripts/upload_nebula_script.sh
  - test/travis_ci_scripts/upload_nebula_script.sh
